### ISSUE TITLE
KeyError on 'name_basics' in s3 example

### ISSUE THREAD

**Issue by jrabek** [cinemagoer/cinemagoer#216]
#### Issue description

Following the steps in https://imdbpy.readthedocs.io/en/latest/usage/s3.html and using the same code produced 

```
2019-05-31 12:58:35,599 CRITICAL [imdbpy] /Users/jrabek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/imdb/__init__.py:714: caught an exception retrieving or parsing "main" info set for mopID "9851526" (accessSystem: s3)
Traceback (most recent call last):
  File "/Users/jrabek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/imdb/__init__.py", line 709, in update
    ret = method(mopID)
  File "/Users/jrabek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/imdb/parser/s3/__init__.py", line 148, in get_movie_main
    persons_cache=_persons_cache)
  File "/Users/jrabek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/imdb/parser/s3/__init__.py", line 114, in _base_person_info
    nb = self.T['name_basics']
KeyError: 'name_basics'
```

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.6.5
- **Postgres:** postgres (PostgreSQL) 11.3
- **IMDbPY:** `6.8dev20190525
- **OS:** uname_result(system='Darwin', node='jesselap1692116.home', release='18.5.0', version='Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64', machine='x86_64', processor='i386')

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

Setup steps:
```
$ pip install git+https://github.com/alberanid/imdbpy
$ s32imdbpy.py data/ postgres://user:password@localhost/imdb
```

Code is directly from https://imdbpy.readthedocs.io/en/latest/usage/s3.html#s3
```
#!python

from imdb import IMDb

ia = IMDb('s3', 'postgres://user:password@localhost/imdb')

results = ia.search_movie('the matrix')
for result in results:
    print(result.movieID, result)

matrix = results[0]
ia.update(matrix)
print(matrix.keys())

```

#### What's the expected result?
Not sure since it errors out.

#### What's the actual result?
KeyError

**Comment by alberanid** [comment]
hi @jrabek , right now I can't reproduce it: the code works on my system.
Can you look for errors on the PostgreSQL logs, while you import the data?

Which tables were created? You should have:
```
# \dt
              List of relations
 Schema |       Name       | Type  |  Owner   
--------+------------------+-------+----------
 public | name_basics      | table | postgres
 public | title_akas       | table | postgres
 public | title_basics     | table | postgres
 public | title_crew       | table | postgres
 public | title_episode    | table | postgres
 public | title_principals | table | postgres
 public | title_ratings    | table | postgres
(7 rows)
```

Thanks for the report.

**Comment by desertzebra** [comment]
Same error. I am using MySQL.

These are the Tables in the db:
![image](https://user-images.githubusercontent.com/2937826/122703794-513b6200-d28d-11eb-8a21-c7eddef847aa.png)

**Version of IMDbPY, Python and OS**

    Python: Python 3.8.5
    Database Server: MySQL ver 8.0.21 for Linux on x86_64
    IMDbPY: 2021.04.18
    OS: uname_result(Linux [PC name] 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

**Steps to reproduce the issue**
_TSV -> MySQL_

`sudo s32imdbpy.py --verbose [data directory] mysql+pymysql://[username]:'[password]'@[ip address for remote MySQL host]:3306/[db name]`

While the sample code (as indicated by OP) also produces this error I used the following code:
from imdb import IMDb

```
ia = IMDb('s3',"mysql+pymysql://rdr:c84BM2&k@163.180.116.83:3306/imdb2rdr")
print("created IMDB class")

results = ia.search_movie('the matrix', results=2000, _episodes=False)
for result in results:
    if('kind' not in result):
        ia.update(result)
    for k in result.keys():
        print(k, '->', result.get(k), end ="," )
    print("")
```
**What's the expected result?**
No errors :)
**What's the actual result?**
```
2021-06-21 12:26:17,274 CRITICAL [imdbpy] /home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py:789: caught an exception retrieving or parsing "main" info set for mopID "11089880" (accessSystem: s3)
Traceback (most recent call last):
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 182, in get_movie_main
    person_data = self._base_person_info(personID,
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 114, in _base_person_info
    nb = self.T['name_basics']
KeyError: 'name_basics'
2021-06-21 12:26:17,283 CRITICAL [imdbpy] /home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py:789: caught an exception retrieving or parsing "plot" info set for mopID "11089880" (accessSystem: s3)
Traceback (most recent call last):
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 182, in get_movie_main
    person_data = self._base_person_info(personID,
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 114, in _base_person_info
    nb = self.T['name_basics']
KeyError: 'name_basics'
```

Additional details
I added a print statement above line 114 to get the following back:
dict_keys(['title_akas', 'title_basics', 'title_crew', 'title_episode', 'title_principals', 'title_ratings'])

Perhaps "self.T" was not updated before the call for 
```
person_data = self._base_person_info(personID, movies_cache=_movies_cache, persons_cache=_persons_cache)
```

**Comment by desertzebra** [comment]
Same error. I am using MySQL.

These are the Tables in the db:
![image](https://user-images.githubusercontent.com/2937826/122703794-513b6200-d28d-11eb-8a21-c7eddef847aa.png)

**Version of IMDbPY, Python and OS**

    Python: Python 3.8.5
    Database Server: MySQL ver 8.0.21 for Linux on x86_64
    IMDbPY: 2021.04.18
    OS: uname_result(Linux [PC name] 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

**Steps to reproduce the issue**
_TSV -> MySQL_

`sudo s32imdbpy.py --verbose [data directory] mysql+pymysql://[username]:'[password]'@[ip address for remote MySQL host]:3306/[db name]`

While the sample code (as indicated by OP) also produces this error I used the following code:
from imdb import IMDb

```
ia = IMDb('s3',"mysql+pymysql://[username]:'[password]'@[ip address for remote MySQL host]:3306/[db name]")
print("created IMDB class")

results = ia.search_movie('the matrix', results=2000, _episodes=False)
for result in results:
    if('kind' not in result):
        ia.update(result)
    for k in result.keys():
        print(k, '->', result.get(k), end ="," )
    print("")
```
**What's the expected result?**
No errors :)
**What's the actual result?**
```
2021-06-21 12:26:17,274 CRITICAL [imdbpy] /home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py:789: caught an exception retrieving or parsing "main" info set for mopID "11089880" (accessSystem: s3)
Traceback (most recent call last):
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 182, in get_movie_main
    person_data = self._base_person_info(personID,
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 114, in _base_person_info
    nb = self.T['name_basics']
KeyError: 'name_basics'
2021-06-21 12:26:17,283 CRITICAL [imdbpy] /home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py:789: caught an exception retrieving or parsing "plot" info set for mopID "11089880" (accessSystem: s3)
Traceback (most recent call last):
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 182, in get_movie_main
    person_data = self._base_person_info(personID,
  File "/home/fahad/.local/lib/python3.8/site-packages/imdb/parser/s3/__init__.py", line 114, in _base_person_info
    nb = self.T['name_basics']
KeyError: 'name_basics'
```

Additional details
I added a print statement above line 114 to get the following back:
dict_keys(['title_akas', 'title_basics', 'title_crew', 'title_episode', 'title_principals', 'title_ratings'])

Perhaps "self.T" was not updated before the call for 
```
person_data = self._base_person_info(personID, movies_cache=_movies_cache, persons_cache=_persons_cache)
```

Edit:
No errors corresponding to this code execution on MySQL

**Comment by desertzebra** [comment]
Just for anyone coming here in future, in my case, I forgot to include the name.basics.tsv.gz dataset, so the name_basics table was not generated.

Thanks for the pointer @alberanid!
