### ISSUE TITLE
invalid block type error

### ISSUE THREAD

**Issue by javadfarah** [cinemagoer/cinemagoer#382]
during extracting IMDb data files get this error on file :title.basics.tsv.gz

invalid block type error

cinemagoer V 2022.2.11
python V 3.10

**Comment by javadfarah** [comment]
update : in imdbpy also same error

```
s32imdbpy.py "/run/media/javadfarah/58EA6D5778ED4F1A/imdb data"     postgresql://moviebox:password@localhost/moviebox
INFO:root:begin processing file /run/media/javadfarah/58EA6D5778ED4F1A/imdb data/name.basics.tsv.gz
INFO:root:processed file /run/media/javadfarah/58EA6D5778ED4F1A/imdb data/name.basics.tsv.gz: 11416506 entries
INFO:root:begin processing file /run/media/javadfarah/58EA6D5778ED4F1A/imdb data/title.akas.tsv.gz
INFO:root:processed file /run/media/javadfarah/58EA6D5778ED4F1A/imdb data/title.akas.tsv.gz: 31043343 entries
INFO:root:begin processing file /run/media/javadfarah/58EA6D5778ED4F1A/imdb data/title.basics.tsv.gz
Traceback (most recent call last):
  File "/home/javadfarah/.local/bin/s32imdbpy.py", line 194, in <module>
    import_dir(dir_name, engine)
  File "/home/javadfarah/.local/bin/s32imdbpy.py", line 179, in import_dir
    import_file(fn, engine)
  File "/home/javadfarah/.local/bin/s32imdbpy.py", line 136, in import_file
    for line in gz_file:
  File "/usr/lib/python3.10/gzip.py", line 399, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 496, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid block type
```

**Comment by javadfarah** [comment]
update: the problem was my files! downloaded again and works like charm!
