### ISSUE TITLE
Windows instructions?

### ISSUE THREAD

**Issue by Chris230291** [cinemagoer/cinemagoer#389]
Hello. I am unable to get this working on windows.
I run `pip install cinemagoer`
and then the example from the readme.

```
PS C:\Users\Chris\Desktop> pip install cinemagoer
Collecting cinemagoer
  Using cached cinemagoer-2022.2.11-py3-none-any.whl (301 kB)
Requirement already satisfied: SQLAlchemy in c:\users\chris\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cinemagoer) (1.4.35)
Requirement already satisfied: lxml in c:\users\chris\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cinemagoer) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\chris\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from SQLAlchemy->cinemagoer) (1.1.2)
Installing collected packages: cinemagoer
Successfully installed cinemagoer-2022.2.11

PS C:\Users\Chris\Desktop> & C:/Users/Chris/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/Chris/Desktop/imdb.py
Traceback (most recent call last):
  File "c:\Users\Chris\Desktop\imdb.py", line 1, in <module>
    from imdb import Cinemagoer
  File "c:\Users\Chris\Desktop\imdb.py", line 1, in <module>
    from imdb import Cinemagoer
ImportError: cannot import name 'Cinemagoer' from partially initialized module 'imdb' (most likely due to a circular import) (c:\Users\Chris\Desktop\imdb.py)
```

Does anyone have and windows specific instructions?

Chris

**Comment by alberanid** [comment]
I think that the problem lies in the fact that you have named your script `imdb.py`, and so the line `from imdb import Cinemagoer` will be a recursive import.

Try renaming it.

**Comment by Chris230291** [comment]
That was the problem. Thanks.
