### ISSUE TITLE
search_movie is not working at all anymore

### ISSUE THREAD

**Issue by vrayv** [cinemagoer/cinemagoer#419]
**Issue description**

Search_movie function returns empty array

**Version of Cinemagoer, Python and OS**

2022.11.27

**Comment by xalienxx** [comment]
Same error happened. I checked all versions since {imdbpy==2021.4.18}

**Comment by xalienxx** [comment]
Log : 

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/imdb/__init__.py", line 831, in update
    ret = method(mopID)
  File "/app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 468, in get_movie_main
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'reference')
  File "/app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 379, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 249, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0816692/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')}
[11/29/2022 07:31:08 PM:pyrogram.dispatcher:235:ERROR] {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0816692/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')}
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 222, in retrieve_unicode
    content = response.read()
  File "/app/.heroku/python/lib/python3.9/http/client.py", line 470, in read
    return self._readall_chunked()
  File "/app/.heroku/python/lib/python3.9/http/client.py", line 580, in _readall_chunked
    value.append(self._safe_read(chunk_left))
  File "/app/.heroku/python/lib/python3.9/http/client.py", line 626, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/app/.heroku/python/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/app/.heroku/python/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/app/.heroku/python/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by smirkybg** [comment]
I confirm too - I get an empty list on doing a query.

**Comment by alberanid** [comment]
we need to check if it's related to #415 or they have changed the HTML.

**Comment by alberanid** [comment]
I confirm this is a change in the HTML.  Fixing it as soon as possible.

**Comment by alberanid** [comment]
a quick fix for movies and persons is in place. Searches for companies and keywords are still broken; I'll work on it in the next few days.

Also, the parser for the people pages are mostly broken, and in general you can expect some bugs and missing information doing search for person and movies.

**Comment by xalienxx** [comment]
Yeh.. 
Also old versions based applications are expecting same issue. 
Do I have to change the code as well or is it enough to just update the cinemagoer package?
Or can I avoid this by creating a cinemagoer based api separately and connecting it with my main application?  My main requirement is to get the imdb poster.

**Comment by WereCatf** [comment]
> Do I have to change the code as well or is it enough to just update the cinemagoer package?

Just updating cinemagoer is enough.

**Comment by smirkybg** [comment]
After 43fa8c469defa307132391928ca3bbfb1b511a01, it seems to be a lot better, but still facing issues:
```
>>> from imdb import Cinemagoer
>>> ia = Cinemagoer()
>>> q = ia.search_movie('Third Person')
2022-12-01 21:08:35,162 CRITICAL [imdbpy] /usr/lib/python3.10/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid title: ""',); kwds: {}
NoneType: None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/imdb/__init__.py", line 450, in search_movie
    res = self._search_movie(title, results)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/__init__.py", line 411, in _search_movie
    return self.smProxy.search_movie_parser.parse(cont, results=results)['data']
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/utils.py", line 432, in parse
    data = self.parse_dom(dom)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/utils.py", line 524, in parse_dom
    return Rules(self.rules).extract(dom)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 317, in extract
    value = self.apply(element)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 455, in apply
    extracted = rule.extract(subroot)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 519, in extract
    list(map(self.extractor.transform, values))
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/searchMovieParser.py", line 64, in <lambda>
    analyze_title(x.get('info', '') + ' (%s)' % x.get('year') if x.get('year') else ''),
  File "/usr/lib/python3.10/site-packages/imdb/utils.py", line 429, in analyze_title
    raise IMDbParserError('invalid title: "%s"' % original_t)
imdb._exceptions.IMDbParserError: invalid title: ""

```

**Comment by xalienxx** [comment]
Yep, IMDbParserError happened when searching for ex: Interstellar (movie),  Foundation (series)

**Comment by alberanid** [comment]
I've pushed a few fixes to improve the situation:
* movies search
* persons search
* keywords search
* companies search

What's still broken:
* we lost the ability to tell a movie from a tv show in search results
* no notes about movies and persons
* a lot of tests fail because the way search results are returned is now different
* Person pages are completely broken; see #421

**Comment by alberanid** [comment]
improved the search movie parser: now it detects movie kind (movie, tv series, short, ...)

**Comment by smirkybg** [comment]
I thought I posted this one too, but I guess not. This is with the latest commit df60f2e6b80a5671d0660dd3025cfdaedbe5d0f0:
```
>>> from imdb import Cinemagoer
>>> ia = Cinemagoer()
>>> q = ia.search_movie('Coach Carter 2005')
2022-12-05 13:10:01,388 CRITICAL [imdbpy] /usr/lib/python3.10/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid title: ""',); kwds: {}
NoneType: None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/imdb/__init__.py", line 450, in search_movie
    res = self._search_movie(title, results)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/__init__.py", line 411, in _search_movie
    return self.smProxy.search_movie_parser.parse(cont, results=results)['data']
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/utils.py", line 432, in parse
    data = self.parse_dom(dom)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/utils.py", line 524, in parse_dom
    return Rules(self.rules).extract(dom)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 317, in extract
    value = self.apply(element)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 455, in apply
    extracted = rule.extract(subroot)
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 519, in extract
    list(map(self.extractor.transform, values))
  File "/usr/lib/python3.10/site-packages/imdb/parser/http/searchMovieParser.py", line 48, in process_title
    analized_title = analyze_title(title)
  File "/usr/lib/python3.10/site-packages/imdb/utils.py", line 429, in analyze_title
    raise IMDbParserError('invalid title: "%s"' % original_t)
imdb._exceptions.IMDbParserError: invalid title: ""

```

**Comment by sandrotosi** [comment]
same as @smirkybg, but i get it with `blood and treasure` and `all rise`

**Comment by sandrotosi** [comment]
and btw i think they've been slowly releasing this new HTML code for a while, since in my code i had to attempt the search multiple time if the returned list was empty

**Comment by sandrotosi** [comment]
not sure if it is the right fix, but i just changed https://github.com/cinemagoer/cinemagoer/blob/master/imdb/utils.py#L429 to `title = ""` just to ensure it's an empty sting and not None or other weird stuff

**Comment by alberanid** [comment]
thanks for the debug. I've just pushed a version with more fixes. Let us know if more title fails.

**Comment by alberanid** [comment]
This issue is no longer relevant due to issue #557: ss of June 2026, Cinemagoer no longer analyzes web pages and can only rely on non-commercial datasets.
