### ISSUE TITLE
Cant fetch "Archer" episodes

### ISSUE THREAD

**Issue by sandrotosi** [cinemagoer/cinemagoer#484]
#### Issue description

I cant fetch episodes for Archer

#### Version of Cinemagoer, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:**  3.11.4
- **Cinemagoer:** 2023.09.23
- **OS:** `uname_result(system='Linux', node='zion', release='6.1.0-9-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)', machine='x86_64')`

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```python
#!/usr/bin/env python

import imdb

ia = imdb.Cinemagoer()
items = ia.search_movie("archer")
archer = [x for x in items if 'kind' in x and x['kind'].startswith('tv ') and x['kind'] != 'tv movie'][0]
ia.update(archer, 'episodes')

```

#### What's the expected result?

`archer` contains the episode information

#### What's the actual result?

```
023-10-10 21:12:48,915 ERROR [imdbpy.parser.http.domparser] /home/USER/.local/lib/python3.11/site-packages/imdb/parser/http/utils.py:438: DOMHTMLSeasonEpisodesParser: caught exception postprocessing data
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.11/site-packages/imdb/parser/http/utils.py", line 436, in parse
    data = self.postprocess_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.local/lib/python3.11/site-packages/imdb/parser/http/movieParser.py", line 2221, in postprocess_data
    episode_seq, episode_title = episode_nr_title.split(" ∙ ")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2023-10-10 21:12:48,919 CRITICAL [imdbpy] /home/USER/.local/lib/python3.11/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing "episodes" info set for mopID "1486217" (accessSystem: http)
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.11/site-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
          ^^^^^^^^^^^^^
  File "/home/USER/.local/lib/python3.11/site-packages/imdb/parser/http/__init__.py", line 665, in get_movie_episodes
    nr_eps += len(other_d['data']['episodes'].get(season) or [])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-6a9188a86888>", line 1, in <module>
    ia.update(archer, 'episodes')
  File "/home/USER/.local/lib/python3.11/site-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
          ^^^^^^^^^^^^^
  File "/home/USER/.local/lib/python3.11/site-packages/imdb/parser/http/__init__.py", line 665, in get_movie_episodes
    nr_eps += len(other_d['data']['episodes'].get(season) or [])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

#### Additional details

-

**Comment by sandrotosi** [comment]
it is because of these spurious (?) episode/season: https://www.imdb.com/title/tt1486217/episodes/?season=Unknown

**Comment by sandrotosi** [comment]
for now i put

```
            if " ∙ " not in  episode_nr_title:
                continue
```

in parser/html/movieparser.py (at line 2221) but there should be a better fix
