### ISSUE TITLE
Cannot search for movie, KeyError 'data'

### ISSUE THREAD

**Issue by Kwieeciol** [cinemagoer/cinemagoer#490]
#### Issue description

Cannot search for movie with a title.

#### Version of Cinemagoer, Python and OS
`cinemagoer==2023.5.1`
Python 3.11.2
Windows 10

#### Steps to reproduce the issue

```python
#!/usr/bin/env python
data = imdb.search_movie_advanced("The Gentlemen", results=5)

print(data)
```

#### What's the expected result?

Some sort of data output.
- 

#### What's the actual result?
Error.
```py
2023-11-15 21:30:26,964 ERROR [imdbpy.parser.http.domparser] E:\GITHUB\sithed-bot\imdb\parser\http\utils.py:438: DOMHTMLSearchMovieAdvancedParser: caught exception postprocessing data
Traceback (most recent call last):
  File "E:\GITHUB\sithed-bot\imdb\parser\http\utils.py", line 436, in parse
    data = self.postprocess_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GITHUB\sithed-bot\imdb\parser\http\searchMovieAdvancedParser.py", line 209, in postprocess_data
    data['data'] = []
    ~~~~^^^^^^^^
TypeError: 'mappingproxy' object does not support item assignment
Traceback (most recent call last):
  File "E:\GITHUB\sithed-bot\movie_data.py", line 156, in <module>
    data = imdb.search_movie_advanced("The Gentlemen", results=5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GITHUB\sithed-bot\imdb\__init__.py", line 485, in search_movie_advanced
    res = self._search_movie_advanced(title=title, adult=adult, results=results, sort=sort, sort_dir=sort_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GITHUB\sithed-bot\imdb\parser\http\__init__.py", line 467, in _search_movie_advanced
    return self.smaProxy.search_movie_advanced_parser.parse(cont, results=results)['data']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
```
- 

#### Additional details

-

**Comment by azmiozgen** [comment]
I have the exact error with,
cinemagoer==2023.5.1
Python 3.9.16
Ubuntu 22.04.3

Any update on this?

**Comment by Kwieeciol** [comment]
> I have the exact error with,
> 
> cinemagoer==2023.5.1
> 
> Python 3.9.16
> 
> Ubuntu 22.04.3
> 
> 
> 
> Any update on this?

I just changed to TMDB, their API is free and probably the same, and they even offer a partnership with JustWatch so you get the watch providers for each movie/show.

**Comment by azmiozgen** [comment]
I'd actually like to go with Cinemagoer. For now, I replaced `search_movie_advanced` function with `search_movie` and it's fine. I believe the error in `search_movie_advanced` is a temporary thing.

**Comment by uyar** [comment]
I've implemented a very basic fix so that we should at least be able to get the link and the title of the search results.

**Comment by uyar** [comment]
Yes, that's why I've called it "very basic" :)  After fixing the episodes parser I didn't have much energy left for the search parser. Both pages are pretty difficult to work with. I'll get to the missing keys later.

**Comment by alberanid** [comment]
This issue is no longer relevant due to issue #557: ss of June 2026, Cinemagoer no longer analyzes web pages and can only rely on non-commercial datasets.
