### ISSUE TITLE
Pulling episodes from series results in KeyError

### ISSUE THREAD

**Issue by periodicta** [cinemagoer/cinemagoer#496]
#### Issue description

Trying to get lists of episodes by season from Cinemagoer, something that worked approximately a year ago through IMDbpy, but I've been getting weird errors.

#### Version of Cinemagoer, Python and OS

MacOS: 14.0
Python version:
3.12.0
Cinemagoer version:
2023.10.22

#### Steps to reproduce the issue

```python
from imdb import Cinemagoer

ia = Cinemagoer()

show = ia.search_movie('friends')[0]

ia.update(show, 'episodes')

print(show['episodes'])
```

#### What's the expected result?

a list of episodes from Friends by season

#### What's the actual result?

```
Traceback (most recent call last):
  File "/home/runner/imdbtesting/main.py", line 9, in <module>
    print(show['episodes'])
  File "/home/runner/imdbtesting/.pythonlibs/lib/python3.10/site-packages/imdb/utils.py", line 1503, in __getitem__
    rawData = self.data[key]
KeyError: 'episodes'
```

**Comment by anilove31** [comment]
same issue

**Comment by gerson-a** [comment]
bumping as i also had the same issue. the sortedEpisodes function also returns an empty list.

**Comment by ItsMeMarc** [comment]
The same with me. Is there any chance to get this issue fixed?
Thanks. :-)

**Comment by anilove31** [comment]
I couldn't find any fix, so I used TMDB instead of IMDB
tmdb has it's own API and almost same library as imdb

**Comment by Tr6666** [comment]
any solution?

**Comment by sbsaylors** [comment]
> TMDB

What python library and/or github project lets you query TMDB?

**Comment by alberanid** [comment]
This issue is no longer relevant due to issue #557: ss of June 2026, Cinemagoer no longer analyzes web pages and can only rely on non-commercial datasets.
